[package]
name = "base58_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2"
sha2 = "0.10.6"
hex = "0.4"
ripemd = "0.1.3"
pbkdf2 = "0.12.2"